2018-11-30 20:46:23,911 ERROR: Exception on /games/add_room [POST] [in /Users/chengyuhan/Documents/GRA/Flask_microblog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/chengyuhan/Documents/GRA/Flask_microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/chengyuhan/Documents/GRA/Flask_microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/chengyuhan/Documents/GRA/Flask_microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/chengyuhan/Documents/GRA/Flask_microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/chengyuhan/Documents/GRA/Flask_microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/chengyuhan/Documents/GRA/Flask_microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/chengyuhan/Documents/GRA/Flask_microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/chengyuhan/Documents/GRA/Flask_microblog/app/games/routes.py", line 83, in add_room
    players = game_player_num[0]
TypeError: 'NoneType' object is not subscriptable
